### ISSUE TITLE
SQL Query issues on specieslists page

### ISSUE THREAD

**Issue by cgendreau** [AtlasOfLivingAustralia/specieslist-webapp#107]
Issue encountered during the CESP ALA workshop:

@nickdos Could probably tell what was the original file.

From our specieslists page:
http://demo.livingatlas.org/specieslists/speciesListItem/list/drt1554365547007

If we click in the menus to the left (Refine results) we get a:

```Unable to retrieve species list items. Please let us know if this error persists. <br>Error:<br>Hibernate operation: could not extract ResultSet; bad SQL grammar [n/a]; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Expression #1 of ORDER BY clause is not in GROUP BY clause and contains nonaggregated column 'specieslists.specieslis2_.item_order' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by```

**Comment by nickdos** [comment]
This is a known issue when an older MySQL driver (?) is installed. @djtfmartin can you explain it better please?

**Comment by cgendreau** [comment]
I think I saw that when migration from 5.6 to 5.7.

**Comment by javier-molina** [comment]
Tested OK with version 3.5-SNAPSHOT, see details below

git.commit.date | 2019-11-01T03:08:19+1100
-- | --
git.commit.id | 0e5311a90fae3545e774ac71b54e5a59b76d7610
git.commit.shortId | 0e5311a
git.branch | HEAD



grails.env | production
-- | --
app.version | 3.5-SNAPSHOT
app.grails.version | 3.2.11
java.version | 1.8.0_222



This an example of faceting that no longer throws a MySQLSyntaxErrorException

I will leave the ticket in QA column and hold until it is part of a non SNAPSHOT version before moving it to Ready
 for CAB

**Comment by javier-molina** [comment]
Working on 3.5.1
