### ISSUE TITLE
My Lists button shows up when not logged in

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/specieslist-webapp#113]
Bug reported by Peter Brenton during manual website testing yesterday:

```
My List function not working

No error message, just not performing the filtering

Returning the default "All lists" view, not filtered to mine only
```

One possibility was that they were not logged in while testing based on attempting to replicate the issue. Two possible solutions are to redirect the "My Lists" button to the login page, or hide it when users are not logged in.

**Comment by nickdos** [comment]
Tested ✅
