### ISSUE TITLE
Add delete button to "my lists"

### ISSUE THREAD

**Issue by M-Nicholls** [AtlasOfLivingAustralia/specieslist-webapp#116]
support ticket: https://support.ehelp.edu.au/a/tickets/37772

The page displaying "My Species Lists" says "Below is a listing of species lists that you have provided. You can use these lists to work with parts of the Atlas. Click on the "delete" button next to a list to remove it from the Atlas".

No "delete button"?

**Comment by djtfmartin** [comment]
There isnt a button as such but there is a "Delete" link.

<img width="1524" alt="Screen Shot 2019-10-04 at 2 12 39 pm" src="https://user-images.githubusercontent.com/444897/66210176-1a847900-e6b1-11e9-9fe2-7afaf8946740.png">

As they are actions, they should be buttons on the right hand side

**Comment by javier-molina** [comment]
Tested as per below. (This was a snapshot version, I think it should be moved to Ready for CAB once a non-SNAPSHOT version is deployed to test.

_ | _ 
-- | --
git.commit.date | 2019-11-01T03:08:19+1100
git.commit.id | 0e5311a90fae3545e774ac71b54e5a59b76d7610
git.commit.shortId | 0e5311a
git.branch | HEAD


_ | _ 
-- | --
grails.env | production
app.version | 3.5-SNAPSHOT
app.grails.version | 3.2.11
java.version | 1.8.0_222


Action links have moved to buttons and work as expected. 

I could argue that combining Bootstrap and browser pop ups is not a good idea but that is not related to this ticket, rather something to consider when species lists has a UI refresh. 

![Screen Shot 2019-11-18 at 5 14 29 pm](https://user-images.githubusercontent.com/8326394/69029019-eb8b5200-0a27-11ea-93ea-4f891fabd653.png)

**Comment by javier-molina** [comment]
Tested on 3.5.1 https://github.com/AtlasOfLivingAustralia/cab/issues/18

**Comment by djtfmartin** [comment]
now deployed in to production.
