### ISSUE TITLE
Searching within a list broken in 3.4 (current production)

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/specieslist-webapp#117]
<img width="1674" alt="Screen Shot 2019-10-07 at 10 44 24 am" src="https://user-images.githubusercontent.com/444897/66301783-a84da780-e8ef-11e9-8318-15efda162e41.png">

```
Unable to retrieve species list items. Please let us know if this error persists. <br>Error:<br>Hibernate operation: could not extract ResultSet; bad SQL grammar [n/a]; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Expression #1 of ORDER BY clause is not in GROUP BY clause and contains nonaggregated column 'specieslist.specieslis2_.item_order' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by
```

**Comment by javier-molina** [comment]
Facets are broken as well.

https://support.ehelp.edu.au/a/tickets/42166 is a ticket related to this issue.

**Comment by ansell** [comment]
Verified this is now working in test:

`https://lists-test.ala.org.au/speciesListItem/list/dr914?fq=family%3ACortinariaceae&max=10`

Broken in production:

`https://lists.ala.org.au/speciesListItem/list/dr914?fq=family%3ACortinariaceae&max=10`

**Comment by javier-molina** [comment]
Tested om on v 3.5.1 https://github.com/AtlasOfLivingAustralia/cab/issues/18
