### ISSUE TITLE
mysql encoding issues with specieslists version >= 3.4 & mysql 5.7

### ISSUE THREAD

**Issue by vjrj** [AtlasOfLivingAustralia/specieslist-webapp#123]
We have some  `Error: Internal Server Error` trying to rematch some old lists or to upload some test list like [this one](https://github.com/AtlasOfLivingAustralia/specieslist-webapp/files/3862267/enconding-issues.csv.txt) with encoding errors like:

```
Caused by: java.sql.SQLException: Incorrect string value: '\xE9\x8C\x90\xE9\xBD\x92...' for column 'common_name' at row 1
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:964)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2487)
        at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1858)
        at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2079)
        at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2013)
        at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5104)
        at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1998)
        at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:204)
        ... 55 common frames omitted
```

This happens to us at least with the last versions of specieslists (>=`3.4`).

More info:
https://thepluginpeople.atlassian.net/wiki/spaces/KB/pages/314867719/MYSQL+exception+-+Caused+by+java.sql.SQLException+Incorrect+string+value

**Comment by vjrj** [comment]
It's caused by the use of the GBIF Backbone Taxonomy that contains Chinese characters:

```
insert into species_list_item (version, author, common_name, data_
resource_uid, date_created, family, guid, image_url, is_published, item_order, kingdom, last_updated, matched_name, list_id, raw_scientific_name) values (0, '(Linnaeus, 1758)', '黑鸛', 'dr7
03', '2019-11-22 00:48:36.314', 'Ciconiidae', '2481909', null, null, 1, null, '2019-11-22 00:48:36.314', 'Ciconia nigra', 21, 'Ciconia nigra') 
```

That is _Ciconia nigra_ in Chinese:
https://www.google.es/search?q=黑鸛

More info:
https://stackoverflow.com/questions/10957238/incorrect-string-value-when-trying-to-insert-utf-8-into-mysql-via-jdbc

**Comment by djtfmartin** [comment]
@vjrj if my memory serves (and it doesnt always) I think we've had some success with using  `utf8mb4` in the past:

https://stackoverflow.com/questions/10957238/incorrect-string-value-when-trying-to-insert-utf-8-into-mysql-via-jdbc

we've done this in workshops, but we've never pushed it back into the ansible repo (as we probably should)....

**Comment by vjrj** [comment]
Thanks Dave, helps a lot.

In fact the database encoding was `latin1`  so changing to `utf8` was enough to solve my issue:

```
ALTER DATABASE specieslists CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE species_list CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE species_list_editors CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE species_list_item CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE species_list_item_species_listkvp CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE species_listkvp CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
```

I think we should specify the encoding in db creation of databases with `encoding` variable  like collectory, specieslists, CAS, etc:
https://docs.ansible.com/ansible/2.5/modules/mysql_db_module.html
so Collections, Lists, User names creation in these languages, don't fail.

BTW I used in the past Chinese and Cyrillic lorem strings in tests to detect these persistence problems. Just coping string from generators like:
http://generator.lorem-ipsum.info/_chinese
and adding an extra utf8 tests.

**Comment by nickdos** [comment]
No change was associated with this issue so moving out of our Kanban board.

I did check `ala-install` and it shows the DB connection as:

```
dataSource.url=jdbc\:mysql\://{{specieslist_db_hostname}}/{{specieslist_db_name}}?autoReconnect=true&connectTimeout=0&useUnicode=true&characterEncoding=UTF-8
``` 

Note the `UTF-8` at end.

**Comment by vjrj** [comment]
The problem is not in the db connection IMHO, but in the db creation encoding in ala-install that is not specified 
https://docs.ansible.com/ansible/2.5/modules/mysql_db_module.html

**Comment by nickdos** [comment]
Thanks for clarifying @vjrj  - would it possible to specify `utf-8` at the DB or table create stage via some extra code in [BootStrap.groovy](https://github.com/AtlasOfLivingAustralia/specieslist-webapp/blob/master/grails-app/init/au/org/ala/specieslist/BootStrap.groovy) maybe? 
Or is this better handled in `ala-install`? 

@djtfmartin any suggestions?

**Comment by vjrj** [comment]
I'll do some tests to have a better understanding of the issue.

**Comment by vjrj** [comment]
Ok I did some tests and I'll send a PR to ala-install in short.

**Comment by nickdos** [comment]
@Rita-C could you check this (code review) and test functionality as part of the next release?

**Comment by Rita-C** [comment]
Added a list `Test 123 黑鸛 `to lists-test, list saved and displayed correctly.

**Comment by nickdos** [comment]
I think this only affects fresh installations with no existing data. @Rita-C could you test locally with empty database, pls?

**Comment by Rita-C** [comment]
Added a list `Test 123 黑鸛` to local empty database, list saved and displayed correctly.

**Comment by vjrj** [comment]
@nickdos and @Rita-C this affected any db created with default encoding (in our case and others deployments was latin1, not utf8). So I'm not sure that you can add 黑鸛 specie in ALA production without re encoding the db. I did: https://github.com/AtlasOfLivingAustralia/specieslist-webapp/issues/123#issuecomment-558964225

**Comment by Rita-C** [comment]
> @nickdos and @Rita-C this affected any db created with default encoding (in our case and others deployments was latin1, not utf8). So I'm not sure that you can add 黑鸛 specie in ALA production without re encoding the db. I did: [#123 (comment)](https://github.com/AtlasOfLivingAustralia/specieslist-webapp/issues/123#issuecomment-558964225)

But I could add this list https://lists-test.ala.org.au/speciesListItem/list/dr12237#list

**Comment by vjrj** [comment]
I don't know when this test db was created. My PR in ala-install setting the utf8 encoding is there since end of december. I know that other previous LA deployments were affected, because I helped to fix it.
