### ISSUE TITLE
Fix the error page to remove the default grails version

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/specieslist-webapp#124]
<img width="724" alt="Screen Shot 2019-11-21 at 9 47 39 am" src="https://user-images.githubusercontent.com/444897/69326603-fa4e5080-0c43-11ea-8b7e-4badb92f98ec.png">

Currently just gives the above for 404 and bad urls

**Comment by djtfmartin** [comment]
Fixed in 3.5.1.

**Comment by javier-molina** [comment]
Now there is a proper Page not found error displayed.

Tested on v 3.5.1 https://github.com/AtlasOfLivingAustralia/cab/issues/18
