### ISSUE TITLE
i18n broken in 3.5

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/specieslist-webapp#125]
Fix provided by @vjrj. Will release 3.5.1 with fix

**Comment by djtfmartin** [comment]
Fixed in 3.5.1. Can be tested by adding ?lang=es to URLs

**Comment by javier-molina** [comment]
I see i18n working for table headings but not much apart from that.

What is the scope of this ticket? 

Looks like there is a long way to make pages fully i18n aware.

**Comment by djtfmartin** [comment]
I think thats it for now really - agree theres probably more work to be done for i18n translations, but the table headings where broken in 3.5, so if you see them working thats it really.

**Comment by vjrj** [comment]
> Looks like there is a long way to make pages fully i18n aware.

@geonb from biodivAtlas Austria and his team were working in improve the internationalization of specieslists these days. I know also that they have some deadline in December, but, @geonb, any idea of where you could send a Pull Request regarding i18n? Thanks!

**Comment by javier-molina** [comment]
Thanks Dave for clarifying the scope and gracias Vicente for the fix and the heads up on what's coming.

**Comment by javier-molina** [comment]
Tested ok in v3.5.1  https://github.com/AtlasOfLivingAustralia/cab/issues/18

**Comment by djtfmartin** [comment]
now deployed in to production.
