### ISSUE TITLE
View record popup display issue

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/specieslist-webapp#128]
The modal popup for viewing a single record has content that overflows the modal window, when a photo is present.

To replicate:
- view a list, e.g. https://lists-test.ala.org.au/speciesListItem/list/dr1782
- find an entry that has a species image thumbnail and click the "info" icon in first column
- note the overflow of content outside the boundary of the modal div (see screenshot below)

I only see this on `lists-test.ala.org.au` which suggests it is a recent regression bug.

![image](https://user-images.githubusercontent.com/532845/70191648-8cc71780-174d-11ea-8923-8ad1f8e08d8b.png)

**Comment by sughics** [comment]
Duplicate of #192 which has been resolved and ready for CAB

**Comment by sughics** [comment]
Closing this as it has been resolved in #192
