### ISSUE TITLE
Add a Delete button for displayed list

### ISSUE THREAD

**Issue by Tasilee** [AtlasOfLivingAustralia/specieslist-webapp#136]
It is way beyond cryptic to be able to **delete** a list you own (or for an admin to delete a list). You have to click on the Name of the list, which takes you to the Data resource, then go to the bottom of the page and find delete. This may remove the resource but doesn't (at least immediately) seem to delete the list.

A DELETE button needs to be added somewhere on the list page. My suggestion would be to either put one in the List info window or adjacent to the download, view occurrence records, view in spatial portal.

In discussion with @nickdos: I was logged in (as admin) and no delete buttons can be seen, but if you go via .../admin, you then see the delete buttons. A bug.

I have been reviewing the (4550!) lists and a serious tidy-up is way overdue. This is step 1.

**Comment by nickdos** [comment]
Yep, agree - should be relatively trivial to add this.

**Comment by nickdos** [comment]
So there are 3 fixes for this:

- [ ] add "My lists" link to top of every page (not just lists home page)
- [ ] afix issue where delete, rematch, reload buttons do not show up
- [ ] aadd a "Delete" button to each list page, if the list is owned by the currently logged-in user (or they are admin) - maybe under the "list info" drop-down area??

**Comment by Tasilee** [comment]
Thanks @nickdos . For the third component. I think it may be consistent if we add a Delete button column that is visible for owned lists or admin? In other words, as we have now for the Admin view of table. This makes it visible and easily actionable.

**Comment by Rita-C** [comment]
https://upsource.ala.org.au/specieslist-webapp/review/SW-CR-4

**Comment by Rita-C** [comment]
@sbearcsiro , could you review my CAS pattern changes, the two commits in ansible-inventories and ala-install, also application.groovy changes?

**Comment by sbearcsiro** [comment]
@Rita-C LGTM

**Comment by ansell** [comment]
The button shows, and clicking on it deletes the list for me on lists-test.ala.org.au with these version numbers showing in buildInfo:

<img width="1658" alt="Screen Shot 2020-04-28 at 2 59 52 pm" src="https://user-images.githubusercontent.com/82365/80448855-f1834880-8960-11ea-8278-f4b5c6f10f12.png">
