### ISSUE TITLE
List type "Local checklist" should be renamed "Area checklist"

### ISSUE THREAD

**Issue by Tasilee** [AtlasOfLivingAustralia/specieslist-webapp#137]
The term "local checklist" has no well-accepted ecological meaning. "Local" is also not appropriate in many situations, for example, a checklist of a region would not be unusual.

The accepted term is "Species checklist" so, if possible, rename "Local checklist" to "Species checklist" as a List type, and rename the associated lists of that type.

**Comment by nickdos** [comment]
I'm wondering if changing both the label and underlying DB value is necessary? My concern is if downline systems are using the DB values via the API, then that functionality could break. Is it possible to query/filter via the API using `local checklist` or `LOCAL_LIST` (code check needed)?

**Comment by nickdos** [comment]
See https://github.com/AtlasOfLivingAustralia/specieslist-webapp/issues/120#issuecomment-610659745

**Comment by Tasilee** [comment]
Currently "local checklist" has no meaning to the ecological, biological, zoological etc communities who understand "species checklists", which doesn't help our reputation (e.g., DQ). I don't want to break  anything so a background work-around is dandy. We had the same problem with the 'download reasons' - the structure of which didn't make sense.

**Comment by Rita-C** [comment]
@nickdos , If only change the label not DB value, what value should be displayed at https://lists-test.ala.org.au/ws for “listType” I guess it should be “LOCAL_LIST” for ws, however, wouldn’t that be confusing as the UI label is "species checklists"?

**Comment by Tasilee** [comment]
Ones of my roles is to point out issues, but not how they are best addressed :)

**Comment by nickdos** [comment]
@Rita-C Might be worth checking the lists.ala.org.au access logs for calls to the WS services that pertain to this... I have a feeling they will all be ALA apps (like BioCollect and maybe Profiles) in which case we don't want them to change, as it will potentially break the API for them. Yes it might be confusing for someone doing a new implementation for the API but seems far less likely than breaking existing dependencies - choose the lesser evil in this case. But look at logs first is my suggestion and then we can make a decision. Note my comment above didn't say to change it but rather suggested we needed to check first before changing it.

**Comment by Rita-C** [comment]
Yes, there are a few ALA apps consume lists webservice API, `biocache-service`, `fieldcapture`, `fieldcapture-hubs`, `biocollect` etc.
I'm going to keep “LOCAL_LIST” for ws, and to add a note on the https://lists-test.ala.org.au/ws page, stating it's equivalent to "species checklists" in UI for backward compatibility reason. How does this sound @nickdos ?

**Comment by nickdos** [comment]
I think that is a good plan 👍

**Comment by Rita-C** [comment]
Updated issue title to ... rename to "Area checklist", ref @Tasilee comment in #120.

**Comment by Rita-C** [comment]
https://upsource.ala.org.au/specieslist-webapp/review/SW-CR-1
