### ISSUE TITLE
Add missing fields to Admin table of lists

### ISSUE THREAD

**Issue by Tasilee** [AtlasOfLivingAustralia/specieslist-webapp#139]
To my knowledge, we have not done a review of all the lists. I have done a preliminary one but I can't do a thorough review without having a table that includes all list db fields. We are currently missing

1. Is private
2. Included in species pages
3. Authoritative
4. Invasive
5. Threatened
6. Part of the sensitive data service
7. Region

Being able to filter and then bulk delete would be next.

Some stats: 38% of lists contain a single taxon, 77% from Spatial Portal (as generic - not good but there is a fix in the next release), 27% are not 'owned', 2% are 'tests'.

**Comment by nickdos** [comment]
I think this needs a separate facet section (to the "List types") to avoid confusion, as some of the labels are similar. Maybe call it "List attributes"(?). 

Requires the fields to be included in the ElasticSearch index before the facets can be used in the UI.

**Comment by Tasilee** [comment]
"List attributes" seems appropriate

**Comment by Rita-C** [comment]
@nickdos @Tasilee , we'll update the filers to have:
1. is private (only visible for admin)
2. included in species pages
3. authoritative (existing)
4. invasive (existing)
5. threatened (existing)
6. part of sensitive data service (existing)
7. region 
8. conservation list (existing)
9. common habitat of species (existing)
10. common trait of species (existing)
11. area checklist (existing)
12. species characters list
13. spatial portal defined list
14. profile list
15. test list
16. other

**Comment by Tasilee** [comment]
Sounds wonderful, thanks @Rita-C

**Comment by Rita-C** [comment]
https://upsource.ala.org.au/specieslist-webapp/review/SW-CR-5
