### ISSUE TITLE
Search function to match on scientific and common names in lists

### ISSUE THREAD

**Issue by m-r-c** [AtlasOfLivingAustralia/specieslist-webapp#14]
Reviving this issue... basic user story is:

> As a user_of list_tool I want to see all species_lists that contain taxon X

Currently this is only possible via the web service https://api.ala.org.au/#ws93. 

Search must find lists that match any of:
- supplied name
- matched scientific name
- matched GUID
- matched common name

Optional feature - add a link from species pages, to the result set for matched name search (create bie-plugin issue if this issue is fixed).

~Implement faceted search for the metadata for species lists using a free text search index (SOLR or Elastic search).~

~It might be worth reviewing indexing all species items with the same index at the same time.~

**Comment by nickdos** [comment]
code QA'ed ✅

**Comment by nickdos** [comment]
I can't get any results from search on test site. Has it been deployed?

**Comment by Rita-C** [comment]
shouldn't be closed

**Comment by nickdos** [comment]
Search performance on test site is quite slow - 20+ seconds to get a response. Do we need to add an index(es) to any of the tables?

**Comment by Rita-C** [comment]
It is slow, wasn't that slow previously. I'll load test data to my local. may need to add new index(es).

**Comment by nickdos** [comment]
Testing seems all good. The only thing that I noticed (probably already there so not fault of this fix) is there is no indication of the number of search results. So if you see 4 pages of results you don't know how many "hits" there are. All our other search interfaces say how many results are returned for a given search. Maybe we just make an enhancement issue for that? Not a high priority.
