### ISSUE TITLE
Upload a list does not require user to be logged in

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/specieslist-webapp#140]
I was able to upload a list without being logged in and I think this is a bug (but not sure). The list gets assigned to the user `info@ala.org.au`. See list example: https://lists.ala.org.au/speciesListItem/list/dr15406.

I think this could be confusing for users, who don't realise they're not logged in and then come back and can't find the list they uploaded, due to it NOT being associated with their user ID.

I suggest the code should be checked for the commit that allowed a non-logged in user to get the account `info@ala.org.au` and see if there is a comment or issue related to that commit.

If nothing found, then make a change that prevents the upload screen being shown to non-logged in users, via an AUTH filter pattern.

@djtfmartin do you recall anything related to this?

**Comment by Rita-C** [comment]
@nickdos , code shows that if a user didn't log in and tried to upload a list via csv, the list username is set to`info@ala.org.au`, the change comment is "work with new bie update to Grails 2.5.1". 
We can hide the "upload a list" button when user is not logged in.

Note, a list can be uploaded without a user name via webservice calls, ref to https://lists.ala.org.au/ws or https://api.ala.org.au/#ws91

**Comment by nickdos** [comment]
I'll check with @adam-collins about the web service side.

On the UI, we should just make the upload page be under AUTH (add its path to the `security.cas.uriFilterPattern` list), so if a user clicks the "upload" button and they're not logged in, they get the login screen first. Hiding the button doesn't stop someone bookmarking the upload page (or getting to it via google).

**Comment by adam-collins** [comment]
Changing the webservice to `security.cas.uriFilterPattern` will require changes to at least the following ALA applications.

- `spatial-hub` is creating lists from the server using `ws/speciesList` and the headers `X-ALA-userId` for userId and `ALA-Auth` for email. 

- `biocollect` is creating lists from the server using `ws/speciesList` with the same userId and email headers but the additional header `Authorization` with the `api key`.

- `phylolink` is creating lists from the server using `ws/speciesList` only with the header `Cookie`.

**Comment by nickdos** [comment]
@adam-collins the idea was NOT for the web service but only the GSP page for uploads to be under `security.cas.uriFilterPattern`.
