### ISSUE TITLE
Missing argument in upload list description

### ISSUE THREAD

**Issue by vjrj** [AtlasOfLivingAustralia/specieslist-webapp#148]
The `Upload List` description, currently looks like:

https://lists.ala.org.au/speciesList/upload
`A species list should consist of a list of scientific or common names and some optional associated properties. Provide input consisting of a header line and some rows of data and we will attempt to map your list to taxon names known to the {0} system. A species list can be uploaded either as a CSV file, or as copy and pasted text.`

Looks like a missing argument (probably my fault).

**Comment by nickdos** [comment]
@Rita-C - just checking whether you've also tested this on test system (not just code review)?
