### ISSUE TITLE
Newly created list shows HTML code in blue Alert box

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/specieslist-webapp#150]
After successfully uploading a list, the list shows a "Confirm" message inside a blue div and the text shows:

> `Alert: <strong>Alert:</strong> All items have been successfully uploaded.`

see: 

![image](https://user-images.githubusercontent.com/532845/82268145-99fd5900-99b1-11ea-8f08-5d56899b3f2b.png)

Fix:
- [ ] remove the repeated `<strong>Alert:</strong>` text

**Comment by Rita-C** [comment]
duplicated issue with #169, closed.
