### ISSUE TITLE
Some lists do not allow viewing by ROLE_ADMIN user

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/specieslist-webapp#154]
As reported by @Tasilee  - https://lists.ala.org.au/speciesListItem/list/dr15655

As an admin I can't access this list - reports:

```
Not authorised
You do not have permission to view this resource
```
I have a feeling they are set as `private`.

**Comment by Rita-C** [comment]
@Tasilee , please try log out then log in again. The list shown for Nick and me after that.

**Comment by nickdos** [comment]
Reviewed ✅
