### ISSUE TITLE
Double colon in the list title

### ISSUE THREAD

**Issue by Rita-C** [AtlasOfLivingAustralia/specieslist-webapp#155]
![Species_list_items___Atlas_of_Living_Australia](https://user-images.githubusercontent.com/29115246/83485675-e5a01e80-a4ea-11ea-9e8c-21f38092695c.png)

**Comment by vjrj** [comment]
My fault, sorry, just remove this colon: 

https://github.com/AtlasOfLivingAustralia/specieslist-webapp/blob/56a21025d7a7d3ec3de79e55601254712a210198/grails-app/i18n/messages.properties#L198

**Comment by Rita-C** [comment]
nw, done that.

**Comment by Rita-C** [comment]
updated as part of #153.

**Comment by nickdos** [comment]
reviewed ✅
