### ISSUE TITLE
Count of number of lists at the top of the page with the table of lists

### ISSUE THREAD

**Issue by Tasilee** [AtlasOfLivingAustralia/specieslist-webapp#158]
When trying to review the status of the lists, it would be helpful if a count of the number of lists in the current table could be displayed at the top of the page. While you can see the number of lists or TYPE and TAG, the combinations cannot be determined. For example, how may lists are 'Authoritative' and 'Invasives'? You can easily get the table by filtering but then have to count the number of lists in the table and in some cases, the number can be large.

**Comment by nickdos** [comment]
There are hard-coded English values, could you please convert them to i18n values, for LA installations.
