### ISSUE TITLE
Add access control to admin functions

### ISSUE THREAD

**Issue by Rita-C** [AtlasOfLivingAustralia/specieslist-webapp#160]
- Only admin user can access` /admin` and its functions
- ~~Add `rematch my lists` link to "My Species List" page for an logged in user to rematch all contributed lists~~
- Add confirmation to `rematch all` ~~and `rematch my lists`~~

**Comment by Rita-C** [comment]
@nickdos @ansell 
Ready for code review and test.

**Comment by nickdos** [comment]
Comments added to commit.

**Comment by ansell** [comment]
My only comment is to agree with Nick on removing the "Rematch my lists" feature because rematching produces some load on specieslist and bie so should only be an admin activity that we can schedule out of hours.

**Comment by nickdos** [comment]
My bad for telling @Rita-C to add the rematch to user's list page. Only when I saw it on test site did I realise it was a bad idea.

**Comment by Rita-C** [comment]
https://upsource.ala.org.au/specieslist-webapp/review/SW-CR-6

**Comment by nickdos** [comment]
Code reviewed ✅

**Comment by nickdos** [comment]
Test site is still forgetting I'm logged in. E.g. I log in and then come back a few hours later and the refresh page and the Login button is showing in the header. When I click the "login" button I'm redirected back to page (I don't see the login screen on auth-test). This suggests the AUTH knows I'm still logged in but lists forgets...

**Comment by nickdos** [comment]
Testing all good ✅
