### ISSUE TITLE
Rectify search/find list item in a given list by scientific name

### ISSUE THREAD

**Issue by Rita-C** [AtlasOfLivingAustralia/specieslist-webapp#163]
- Change the search on species list items page to something like search/find items by scientific name
- Expand the search to search more fields, i.e. scientific name, supplied name, common name
- ~~Expand the search to search KVP if possible~~

![Screen Shot 2020-07-16 at 1 26 54 pm](https://user-images.githubusercontent.com/29115246/87623309-76b01980-c768-11ea-91ba-acc0389d7f00.png)

[https://lists.ala.org.au/speciesListItem/list/dr494](url)

**Comment by Rita-C** [comment]
shouldn't be closed

**Comment by nickdos** [comment]
Testing: looks good to me ✅
