### ISSUE TITLE
Incorrect facet count on "my lists" page

### ISSUE THREAD

**Issue by Rita-C** [AtlasOfLivingAustralia/specieslist-webapp#165]
A defect introduced by changes of #153

Steps to reproduce:

1. go to lists page, log in if prompted e.g. https://lists-test.ala.org.au
2. click "My lists" button
3. check facets on the left hand side

Expected results: facet counts match the numbers of the displayed lists

Actual results: facet counts do not match

**Comment by nickdos** [comment]
The only commit to this issue (43899d7) is a code formatting change only (functionally equivalent). Is there another commit?

**Comment by Rita-C** [comment]
This is the only commit, it's not only code formatting change, one param is added then removed, refer to code comment below:
```
/now remove the params that were added
            //params.remove('username')
            params.remove('userId')
```

**Comment by nickdos** [comment]
Thanks - got it now.
