### ISSUE TITLE
Browser back button does not work when viewing a list

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/specieslist-webapp#175]
Testing in FireFox on Mac.

If you click through to a list from the home page and then try clicking the browser back button, the browser does not return to the full list of lists page.

This seems to be due to the individual list page triggering a redirect to itself and thus hitting the back button goes to previous viewing of the same page, which in turn triggers a reloading of the page (redirect). Thus the cycle continues and you can't get back to the full listing without using the history or via the crumbtrail. See screenshot where the individual list page appears twice in the history.

![image](https://user-images.githubusercontent.com/532845/92668088-2365dc00-f351-11ea-9690-5b3ed68ce47d.png)

The redirect needs to be removed - there is probably a reason it was added but there needs to be another way of achieving the same outcome.

**Comment by Rita-C** [comment]
Back button not working, it’s due to a line added in June 2019:
```
window.onhashchange = loadGridOrList;
```
so clicking “back” button with hash part of the url only reloads list or grid view.

there is no ticket or reason I could see the reason behind the change.

**Comment by nickdos** [comment]
Work-around (hack) could be to trigger `history.back()` after that line (101). Might not work but something easy to try?

**Comment by nickdos** [comment]
This is a priority if working on the code - such an annoying bug!

**Comment by nickdos** [comment]
CR and testing DONE.
