### ISSUE TITLE
Update search place holder text

### ISSUE THREAD

**Issue by Rita-C** [AtlasOfLivingAustralia/specieslist-webapp#176]
to include new searchable fields added by #14 

    supplied name
    matched scientific name
    matched GUID
    matched common name

**Comment by Rita-C** [comment]
Hi @nickdos , I noticed the `search` place holder was not updated while showing the changes to Verity yesterday, I made the change locally (also changed the place holder for `find` on the species items page for consistency), as shown in the screen shots, are you happy with the wordings?

![Screen Shot 2020-09-16 at 5 29 36 pm](https://user-images.githubusercontent.com/29115246/93404860-ba411400-f8ce-11ea-9259-d81b40aa2ebd.png)
=========================================================================================
![Screen Shot 2020-09-16 at 5 29 25 pm](https://user-images.githubusercontent.com/29115246/93404866-bf9e5e80-f8ce-11ea-8b46-35e8685a3355.png)

**Comment by Rita-C** [comment]
code review at https://upsource.ala.org.au/specieslist-webapp/review/SW-CR-7

**Comment by nickdos** [comment]
Code review done. Testing looks good to go.
