### ISSUE TITLE
Offset argument not cleared from URL when refining Lists search results

### ISSUE THREAD

**Issue by timhicks-ala** [AtlasOfLivingAustralia/specieslist-webapp#180]
To reproduce:

- https://lists.ala.org.au/public/speciesLists?q=epbc&max=25&sort=listName&order=asc&offset=25
- This is a search for lists containing "epbc", on page 2 of results (offset=25)
- Click "Conservation list (10)" or "List of sensitive species (2)" under "Refine Results"
- Search now erroneously shows "No species found" - URL is https://lists.ala.org.au/public/speciesLists?q=epbc&max=25&sort=listName&order=asc&offset=25&listType=eq:CONSERVATION_LIST
- Removing "&offset=25" from list moves back to the first page of results and does show the conservation list results.

To fix:

- When additionally refining/filtering search results in Lists, remove any offset from the URL to ensure the new search starts from page 1 of results, rather than a theoretical page 2 or higher, where no results may show if there are insufficient results to populate multiple pages.

**Comment by Rita-C** [comment]
Hi @nickdos can you please code review?

**Comment by nickdos** [comment]
> Hi @nickdos can you please code review?

Done ✅

**Comment by Rita-C** [comment]
Hi @nickdos , change deployed to lists-test, please QA

**Comment by nickdos** [comment]
Pagination now not working as expected. Clicking to page 2, shows the results for page 2 but the pagination buttons are displayed as if it was page 1:

![image](https://user-images.githubusercontent.com/532845/114975438-975bfa00-9ec7-11eb-8cdf-54681d40832f.png)

**Comment by Rita-C** [comment]
Please test again @nickdos

**Comment by nickdos** [comment]
All good now ✅
