### ISSUE TITLE
Slow performance viewing large lists

### ISSUE THREAD

**Issue by timhicks-ala** [AtlasOfLivingAustralia/specieslist-webapp#182]
Viewing lists with large numbers of entries is quite slow, for example this one with over 3,000 items: https://lists.ala.org.au/speciesListItem/list/dr2505#list

It seems to be loading/querying all list items at once, rather than the ten shown by default on a single page. Loading this and other large lists takes long enough for Chrome to show a "Page unresponsive" warning - this includes the first page and all subsequent pages. The time it takes to clear this warning and display the results seems to increase the larger a list is.

**Comment by Rita-C** [comment]
Investigated the issue, only 10 items (defined by per page) were returned on a single page. The page, however, queried the database on facets, total matched count, no-match count, distinct count, etc.

Firefox seemed quicker (7.93s) compares to Chrome (27.63s)

**Comment by Rita-C** [comment]
Loading images from `images.ala.org.au` redirected to `s3` slows down page loading.

**Comment by nickdos** [comment]
Are the code changes for this on the `grails 4` branch?

**Comment by Rita-C** [comment]
yes
