### ISSUE TITLE
Selecting multiple list types facets throws error

### ISSUE THREAD

**Issue by Rita-C** [AtlasOfLivingAustralia/specieslist-webapp#190]
https://lists.ala.org.au/public/speciesLists?q=test&max=25&sort=listName&order=asc&listType=eq%3ACONSERVATION_LIST&listType=eq%3ACONSERVATION_LIST

Steps to re-produce:
1. Go to `https://lists.ala.org.au/public/speciesLists`
2. Select "Conservation list" from the refine lists facets
3. Once the page is loaded, select another list type, e.g. "Test list" from the facets
 
Expected results:
Page loaded with the filtered lists

Actual results:
"Something went wrong" error displayed

=============================================
Discussed with @nickdos , we decided to be consistent with other ALA applications (e.g. Biocollect), only display selected list type in the selected facet section, the user needs to remove the selected filter before selecting a different list type.

**Comment by nickdos** [comment]
Code ✅

**Comment by nickdos** [comment]
LG on test
