### ISSUE TITLE
"q=null" in removing filter URL caused incorrect list filtering results

### ISSUE THREAD

**Issue by Rita-C** [AtlasOfLivingAustralia/specieslist-webapp#191]
Steps to reproduce:
1. Go to `https://lists.ala.org.au/public/speciesLists`
2. Select "Conservation list" from the refine lists facets
3. Click "Conservation list"  to remove this filter

Expected results:
Filter removed, all [public] lists displayed

Actual results:

- Only some lists are displayed due to `&q=null` in the removing filter URL
- "null" as search text in the search input field

**Comment by nickdos** [comment]
Code ✅

**Comment by nickdos** [comment]
LGTM on test
