### ISSUE TITLE
Upload page showing German warning text

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/specieslist-webapp#193]
On prod, when uploading a list, the warning text includes a German translation: `**Achtung** No species name column could be found`

![image](https://user-images.githubusercontent.com/532845/141377459-c763ca44-71eb-4cd6-9706-7b3814974828.png)

**Comment by Rita-C** [comment]
same issue as #187?

**Comment by nickdos** [comment]
Looks like same issue, yes.

**Comment by nickdos** [comment]
Closing as dupe for #187
