### ISSUE TITLE
Enhancement for the more accurate name match

### ISSUE THREAD

**Issue by Rita-C** [AtlasOfLivingAustralia/specieslist-webapp#199]
lists has been updated to use `namematching-ws.ala.org.au/` for name matching.

Enhancement to use user supplied other terms, including kingdom, phylum, class, order and possibly author as well as family. This will allow list users to be a bit more accurate.

**Comment by charvolant** [comment]
Possible names for higher-order things like family, etc.

kingdom: regnum
phylum: divisio, division
class: classis, clazz, class_, classs
order: ordo
family: familia
genus: genericEpithet, generic epithet

**Comment by charvolant** [comment]
Example lists with additional ranks

https://lists.ala.org.au/speciesListItem/list/dr5363
https://lists.ala.org.au/speciesListItem/list/dr4778
https://lists.ala.org.au/speciesListItem/list/dr17880
https://lists.ala.org.au/speciesListItem/list/dr7933 - this feeds into the name index and contains higer taxonomy for that reason
https://lists.ala.org.au/speciesListItem/list/dr487

**Comment by Rita-C** [comment]
deployed to lists-test @nickdos , @charvolant .

**Comment by nickdos** [comment]
Did you mean to close the issue as well as the PR? Issue is still in QA column...

**Comment by Rita-C** [comment]
Think merging PR closed the issue, reopened.

**Comment by charvolant** [comment]
[ALA_Common_Names.csv](https://github.com/AtlasOfLivingAustralia/specieslist-webapp/files/7657819/ALA_Common_Names.csv)

Does not seem to load properly. `Unable to parse species list data: String index out of range: 0` I'm not sure if this is a pre-existing bug or not.

[ALA_Additional_Taxa.csv](https://github.com/AtlasOfLivingAustralia/specieslist-webapp/files/7657825/ALA_Additional_Taxa.csv)

Loads correctly.

**Comment by Rita-C** [comment]
Thanks @charvolant , deleting the empty column between "status" and "temporal" in ALA_Common_Names.csv fixed the problem.

**Comment by charvolant** [comment]
Oopsie
