### ISSUE TITLE
Missing 'master' branch

### ISSUE THREAD

**Issue by vjrj** [AtlasOfLivingAustralia/specieslist-webapp#203]
Currently there isn't a  `master` branch in this repository so our ala-i18n task is failing. Can we add a conventional `master` branch?

Thanks

**Comment by vjrj** [comment]
cc @Rita-C TIA!

**Comment by Rita-C** [comment]
Thanks for letting us know @vjrj . @matthewandrews has restored the master branch.

**Comment by vjrj** [comment]
Thanks indeed @Rita-C and @matthewandrews
