### ISSUE TITLE
Updating attribute values for a species list item seems to remove the value upon update

### ISSUE THREAD

**Issue by sughics** [AtlasOfLivingAustralia/specieslist-webapp#209]
In the screenshot below, the pca1 attribute has been updated to `5.33`
![Screen Shot 2022-05-25 at 11 45 30 am](https://user-images.githubusercontent.com/105408469/170161786-0b711d3c-e9fb-4b66-94e3-54786e8e7485.png)

Once the changes are saved and the page is reloaded, the value is no longer there (ield  is empty): 
![Screen Shot 2022-05-25 at 11 47 12 am](https://user-images.githubusercontent.com/105408469/170161985-3296ae87-c13d-4298-8f1b-c1d1f3bb1f2d.png)

Only the changes made to the 'Supplied Name' attribute is actually updated as expected.

**Comment by adam-collins** [comment]
https://github.com/AtlasOfLivingAustralia/specieslist-webapp/pull/249

**Comment by sughics** [comment]
Released with [4.1.0](https://github.com/AtlasOfLivingAustralia/specieslist-webapp/releases/tag/4.1.0)
