### ISSUE TITLE
Authoritative list seems to be returning 69 records vs 71

### ISSUE THREAD

**Issue by patkyn** [AtlasOfLivingAustralia/specieslist-webapp#212]
https://lists.ala.org.au/ws/speciesList?isAuthoritative=eq:true&max=1000 seems to be returning inconsistent results. There should be 71 lists but it has been returning 69 lists instead. This has caused some speciesList to disappear, mainly affecting, dr872 and dr1787 so far.

![image](https://user-images.githubusercontent.com/1606595/181132442-7f61ccfa-caef-4c96-8b53-97dc52727840.png)

![image](https://user-images.githubusercontent.com/1606595/181134729-e92c13f9-db06-454a-a5f4-8c0caa8954e7.png)

This happened few times in the mornings, when the pipelines full indexing runs. 
![image](https://user-images.githubusercontent.com/1606595/181134469-24798b84-963d-4592-bf73-d3d782e5a761.png)

**Comment by adam-collins** [comment]
Species was updated. The webservice is returning 71 records today.
