### ISSUE TITLE
OIDC Integration 

### ISSUE THREAD

**Issue by sughics** [AtlasOfLivingAustralia/specieslist-webapp#213]
- Migrate to Java 11.
 - OIDC Integration
 - Open API Specs

**Comment by sughics** [comment]
Function testing document: https://confluence.csiro.au/display/ALASD/Species+lists+testing for application version 4.0.1-SNAPSHOT

**Comment by TaniaGLaity** [comment]
undertook UIA  - passed apart from know issues with test pointing to spatial prod

[ListsUI testing Aug22.docx](https://github.com/AtlasOfLivingAustralia/specieslist-webapp/files/9357290/ListsUI.testing.Aug22.docx)

**Comment by sughics** [comment]
Currently holding back on deployment due to ws authentication backwards compatibility issue found during functional testing with BioCollect. Bruce H in the process of implementation a solution in ala-ws-security-plugin

**Comment by sughics** [comment]
OIDC changes now deployed

**Comment by TaniaGLaity** [comment]
Great ta
