### ISSUE TITLE
Speices list "View occurrence record" broken for dr487

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/specieslist-webapp#22]
_From @djtfmartin on August 19, 2014 11:40_

*migrated from:* https://code.google.com/p/ala/issues/detail?id=258
*date:* Wed Sep  4 21:08:11 2013
*author:* moyesyside
 ---

[http://lists.ala.org.au/speciesListItem/listAuth/dr487](http://lists.ala.org.au/speciesListItem/listAuth/dr487)

click "View occurrence record" 

Get

Error 500: Internal Server Error

_Copied from original issue: AtlasOfLivingAustralia/biocache-hubs#43_

**Comment by nickdos** [comment]
_From @mbohun on August 19, 2014 11:40_


*date:* Wed Sep  4 23:43:04 2013
*author:* natasha....@csiro.au
 ---

This is a bug with the biocache-service it is not handling lsid:"ALA_Amytornis_textilis_modestus" correctly:

See [http://biocache.ala.org.au/occurrences/search?q=lsid:%22ALA_Amytornis_textilis_modestus%22](http://biocache.ala.org.au/occurrences/search?q=lsid:%22ALA_Amytornis_textilis_modestus%22)

As opposed to : 
[http://biocache.ala.org.au/occurrences/search?q=lsid:ALA_Amytornis_textilis_modestus](http://biocache.ala.org.au/occurrences/search?q=lsid:ALA_Amytornis_textilis_modestus)

There is a quick fix that I will work in the species_list tool. Change the lsid: query components to NOT be quoted. The lsid tag is handled specially anyway and will automatically substitute the left right values in the query. 

Are you happy for the quick fix on list tool?  I will fix the other issue on biocache-service for the next release.



 ---
**UPDATES:**
*Status:* Started

**Comment by nickdos** [comment]
_From @djtfmartin on August 19, 2014 11:40_


*date:* Wed Sep  4 23:43:57 2013
*author:* moyesyside
 ---

sounds fine to me

**Comment by nickdos** [comment]
_From @mbohun on August 19, 2014 11:40_


*date:* Wed Sep  4 23:51:19 2013
*author:* natasha....@csiro.au
 ---

Changes committed to list tool. Issue to remain open until fixed in biocache-service.

**Comment by nickdos** [comment]
_From @djtfmartin on August 19, 2014 11:40_


*date:* Tue Oct  1 21:16:02 2013
*author:* moyesyside
 ---

fixed?

**Comment by nickdos** [comment]
_From @mbohun on August 19, 2014 11:41_


*date:* Wed Oct  2 15:59:38 2013
*author:* natasha....@csiro.au
 ---

Fixed on dev:
[http://biocache-test.ala.org.au/ws/occurrences/search?q=lsid:%22ALA_Amytornis_textilis_modestus%22&facet=off](http://biocache-test.ala.org.au/ws/occurrences/search?q=lsid:%22ALA_Amytornis_textilis_modestus%22&facet=off)

Just need to release to production.

 ---
**UPDATES:**
*Status:* OnDev

**Comment by nickdos** [comment]
Prod list tool is now throwing a different Grails error - moving to list tool issues.

**Comment by djtfmartin** [comment]
Seems to be working. closing.
