### ISSUE TITLE
Species List Security vulnerabilities

### ISSUE THREAD

**Issue by sat01a** [AtlasOfLivingAustralia/specieslist-webapp#220]
EDIT: Addressed and deployed as part of 4.0.2 release.

Two vulnerabilities were discovered in species list recently during testing and upgrades.

- CHECK EMAIL - functionality and data provided by `/ws/checkEmailExists` is returning info on users if a valid email address provided for user in our userdetails database . This is available for  anyone who requests the resource (no auth required). 

 - SAVE LIST via Webservice - When saving lists via the ws, which calls saveList() in WebServiceController, the request is not authenticated. Instead of checking the provided userId and api key, the method saveList instead just reads the username sent by the requestor on the cookie  and saves the uploaded list under that username. This allows any requestor from saving a list as long as they provide a email which exists in the ala userdetails database. This allows a requestor to upload a list under someone else's username.

**Comment by sughics** [comment]
Fixe and released with 4.0.2
