### ISSUE TITLE
List CSV Upload UI does not recognise header row

### ISSUE THREAD

**Issue by temi** [AtlasOfLivingAustralia/specieslist-webapp#23]
While uploading list from CSV file, list tool only recognises header row when it matches known vocabulary term like 'scientific name'. It is useful to ignore this check from PhyloLink perspective since first row will always be header value and might not have know vocabulary name in it.

**Comment by ben3000** [comment]
Do you have an example of PhyloLink output, and what should it do instead?

**Comment by temi** [comment]
@ben3000 Phylolink does not require this feature anymore. It can be closed.

**Comment by ben3000** [comment]
So it is safe to assume that if no matching species name column can be found, that the tool does not process the incoming data?

**Comment by temi** [comment]
Yes, lists tool requires species name column.

**Comment by ben3000** [comment]
See https://github.com/AtlasOfLivingAustralia/specieslist-webapp/commit/a546442c1b51299e3fe307d8d4a09fdd39a5b8ff.
