### ISSUE TITLE
Lists returns different sets based on query parameter order

### ISSUE THREAD

**Issue by sat01a** [AtlasOfLivingAustralia/specieslist-webapp#230]
This query returns an expected list of state and national conservation lists: 

https://lists.ala.org.au/public/speciesLists?&max=25&sort=listName&order=asc&listType=eq:CONSERVATION_LIST&isThreatened=eq:true&isAuthoritative=eq:true

This query returns a weird mix of private lists and unwanted results: 

https://lists.ala.org.au/public/speciesLists?&max=25&sort=listName&order=asc&isAuthoritative=eq:true=&isThreatened=eq:true&listType=eq:CONSERVATION_LIST

The only difference seems to be the order of parameters. This means that clicking the flags on the lists tool returns unexpected results.

**Comment by sat01a** [comment]
Added to the board - (cc @peggynewman )

**Comment by sughics** [comment]
This does not necessarily seem to be an issue with the parameter order  - in the second request, the there is an additional misplaced`=` within `&isAuthoritative=eq:true=` which is causing the results to be different. When this character is removed, both of the URLs listed above retrn the same values in the same order regardless of the url parameter order. 

Looking at the lists UI, some filters are still available to select when they have already been selected. If selected again, a duplicate param is added to the url - returning incorrect results and eventually result in a 400 error. 
The misplaced `=` mentioned earlier  might have been an artefact of the issue described above. 


![Image](https://user-images.githubusercontent.com/105408469/208579260-fe7921aa-8776-4894-a783-ebab2e8894f2.png)

**Comment by sughics** [comment]
Also related to https://github.com/AtlasOfLivingAustralia/specieslist-webapp/issues/232

**Comment by peggynewman** [comment]
Cheers @sughics, I do recall finding the isAuthoritative flag showing up twice, so I think you're right about selecting the filters twice being weird.

**Comment by sughics** [comment]
Duplicate facet removal fix implemented here: https://github.com/AtlasOfLivingAustralia/specieslist-webapp/pull/233

**Comment by sughics** [comment]
> Cheers @sughics, I do recall finding the isAuthoritative flag showing up twice, so I think you're right about selecting the filters twice being weird.

Turns out the logic behind displaying the **unchekced** tag facets i.e. boolean facets (`isAuthoritative, isThreatened, isInvasive, isSDS, isBIE, isPrivate)` did not check to determine whether they were already selected  - resulting in an unchecked facets for the above facet list always being displayed.  The fix  above should address this.
