### ISSUE TITLE
List update removes list flags

### ISSUE THREAD

**Issue by sat01a** [AtlasOfLivingAustralia/specieslist-webapp#231]
When reloading a list the list flags are switched off in the metadata. 

This means the list values are no longer indexed (eg for stateconservation and countryconservation) unless we notice. This is Really Bad.

I think other metadata might be removed as well eg. Region

Raised by - @peggynewman

**Comment by sat01a** [comment]
Ready for review + will be deployed with public and private improvements

**Comment by adam-collins** [comment]
https://github.com/AtlasOfLivingAustralia/specieslist-webapp/pull/241

**Comment by sughics** [comment]
Included in release 4.1.0
