### ISSUE TITLE
Spaces added to column names 

### ISSUE THREAD

**Issue by rosemaryjoconnor** [AtlasOfLivingAustralia/specieslist-webapp#237]
When a column name has capitalised acronyms the acronym is expanded with spaces between each letter. 
For example: 
https://lists.ala.org.au/speciesListItem/list/dr656
We had to name the column 'iucn Red List' rather than 'IUCN Red List' as the latter would result in 'I U C N Red List' as the column name. As can be seen in this list it means we also need to expand out state acronyms or have them in lower case. So 'NSW' has to be 'nsw' or 'New South Wales' in order to be readable. 

The image below shows a valid field name 'TS ProfileID' being displayed incorrectly

![image](https://user-images.githubusercontent.com/99848596/218595027-1c690fd9-4c23-4abc-a7a4-a64043799782.png)

Could this please be fixed.

**Comment by adam-collins** [comment]
https://github.com/AtlasOfLivingAustralia/specieslist-webapp/pull/249

**Comment by sughics** [comment]
Included in release 4.1.0
