### ISSUE TITLE
check data button returns error 

### ISSUE THREAD

**Issue by temi** [AtlasOfLivingAustralia/specieslist-webapp#24]
I uploaded a csv file and clicked check data button. it returned the following error.
```
Error: Internal Server Error (500)
URI
/speciesList/parseData
Class
java.io.IOException
Message
mark/reset not supported
```

**Comment by m-r-c** [comment]
This was fixed a while ago but never got deployed.

A new version was released yesterday, so it should be ok now. Please retest.

**Comment by temi** [comment]
It is working. thanks!
