### ISSUE TITLE
Lists tool - Supplied vernacularName, CommonName not retained on upload

### ISSUE THREAD

**Issue by rosemaryjoconnor** [AtlasOfLivingAustralia/specieslist-webapp#246]
Lists tool is removing supplied fields such as vernacularName (Vernacular name) and CommonName (Common name) if they are supplied in the upload file. Common name is populated via matching and if either of the above are supplied they are not being retained.

This is problematic for our authoritative lists as supplied fields may be specific to the local region for Conservation or Sensitive data and need to be retained.

Could this please be investigated.

**Comment by adam-collins** [comment]
Uploaded lists will always have additional columns added. There will always be a problem when the upload file has columns with the same names as the columns added by lists. 

It would be worthwhile noting this issue on the upload page after a UI review `https://lists.ala.org.au/speciesList/upload`

The solution is to rename the conflicting columns before uploading. Please confirm that this works.

**Comment by nickdos** [comment]
Hi @rosemaryjoconnor - can we close this issue, as I note the related [1004](https://github.com/AtlasOfLivingAustralia/ala-infrastructure/issues/1004) has been closed?

**Comment by rosemaryjoconnor** [comment]
@nickdos I'll have a word with Amanda Buyan and see if this is still an issue.

**Comment by rosemaryjoconnor** [comment]
@nickdos Amanda has done some testing for authoritative lists. As long as vernacularName is used to represent the common name the state gives a species, and then the Common Name (Matched) is what the ALA comes up with.  Not the most ideal but is a workaround. She has updated her code and documentation accordingly.
I'll close this off now thank.
