### ISSUE TITLE
Lists Admin mode - filters incorrect

### ISSUE THREAD

**Issue by rosemaryjoconnor** [AtlasOfLivingAustralia/specieslist-webapp#247]
For lists.ala.org.au when you go into Admin mode, the 'Authoritative Lists' and 'Sensitive Data Service' checkboxes are not available. The filter list is duplicated.

 This is all ok in lists-test.ala.org.au.
![lists-admin-prod](https://github.com/AtlasOfLivingAustralia/specieslist-webapp/assets/99848596/66beae92-5de9-444e-9a72-b24d660ebeaf)
![lists-test-admin-prod](https://github.com/AtlasOfLivingAustralia/specieslist-webapp/assets/99848596/5bf40ea8-0a14-4a68-bba9-6ae166597db7)

Can this be fixed please.
Please see attached screenshots

**Comment by peggynewman** [comment]
@rosemaryjoconnor I believe this is a duplicate of https://github.com/AtlasOfLivingAustralia/specieslist-webapp/issues/232 
and a fix is in test on it's way to prod already

**Comment by rosemaryjoconnor** [comment]
Ah ok sorry, I'll close it
