### ISSUE TITLE
Field guides and other list content not appearing in prod view for BIE species pages

### ISSUE THREAD

**Issue by aliciadoddy** [AtlasOfLivingAustralia/specieslist-webapp#260]
It appears that a lot of lists information has disappeared from prod in the BIE, including field guide content, among others. However, this information is all still appearing in test. See examples below-

Prod
https://bie.ala.org.au/species/https://biodiversity.org.au/afd/taxa/2a4e373b-913a-4e2a-a53f-74828f6dae7e#overview

Test
https://bie-test.ala.org.au/species/https://biodiversity.org.au/afd/taxa/2a4e373b-913a-4e2a-a53f-74828f6dae7e#overview

Can this please be investigated, and the lists content returned to production. Cheers

**Comment by sughics** [comment]
Issue reported and resolved here: https://github.com/AtlasOfLivingAustralia/specieslist-webapp/issues/257
