### ISSUE TITLE
Some List parameters are not sorting correctly

### ISSUE THREAD

**Issue by Tasilee** [AtlasOfLivingAustralia/specieslist-webapp#27]
(admin access)

Set 'items/page' = 100  (an 'All' setting would be hendy here)
I expect clicking on header item would toggle Sort A-Z with Z-A but this doesn't happen as far as I can tell.

E.g., 

Clicking on 'List type' - top of list is "test list" when I would expect "checklist for local"
Clicking on 'List type' again - I get "species with a common habitat"

Authoritative works as expected

Owner doesn't sort properly

Date submitted works as expected but table layout changes on paging

Item count works as expected

**Comment by sat01a** [comment]
@temi Can you pls add upsource url?

**Comment by temi** [comment]
https://upsource.ala.org.au/specieslist-webapp/review/SW-CR-4
