### ISSUE TITLE
Missing taxons, genus, phylum, class, order etc when importing list from a file

### ISSUE THREAD

**Issue by qifeng-bai** [AtlasOfLivingAustralia/specieslist-webapp#279]
@charvolant  reports  a number of columns missing in KVPs when uploading a species list. 

For example:
When a name is matched, 

Scientific Name (matched)Common Name (matched) | Family (matched) | Kingdom (matched) will be replaced 

other fields which currently are missing, e g. 
Taxon Rank | Genus| raw Phylum | raw Class | raw Order etc

Also expected to see:
raw Kingdom | raw Family  etc

See examples:

Doug's workaround:
https://lists-test.ala.org.au/speciesListItem/list/dr21996?max=10

**Other changes**
Store the original header names as keys, no more camelcase conversion, (Required by Doug) e.g.I
In previous version,  
"commName" is also converted to "vernacular name"
"profileNo" is converted to "profile no"

And we accept the different variants of "vernacular name", such as "commonName, common, vernacular..". In new version, we still interpret this way, we store the 'original name' as key of KVs.

**Comment by qifeng-bai** [comment]
Todo:
Requires database level changes

**Comment by nickdos** [comment]
Hi @qifeng-bai - is this still in-progress? 

I'm also a bit confused by this ticket, as the "other fields which currently are missing" are never generated, when you create a new list. AFAICT those fields are no different to any arbitrary KVP fields the user might include like "colour" or "body length".

**Comment by qifeng-bai** [comment]
@nickdos  It should be marked as completed.  "The rest of fields" should be stored as KVP in List
