### ISSUE TITLE
Failure when rematching a large number of lists

### ISSUE THREAD

**Issue by adam-collins** [AtlasOfLivingAustralia/specieslist-webapp#304]
When using the admin button `rematch all`, it can fail on smaller machines when there are a large number of lists. This should not happen. There is a workaround implemented but this workaround is not ideal as it involves restarting tomcat.

During a rematch all, existing name matches are first removed, then items are iterated, with batches sent to namematching service.

For this issue, make changes to `rematch all`.
- Perform an update to existing matches only after a diff. This is instead of the removal of matches at the beginning of the `rematch all`.
- Use smaller transaction boundaries and wait for the database flush to complete.
- Enable parallel updates with a configurable number of threads.
- Iterate over lists before individual list items. This is instead of iterating through list items only.

**Comment by qifeng-bai** [comment]
#288

**Comment by qifeng-bai** [comment]
Q: Iterate over lists before individual list items. This is instead of iterating through list items only.
A: nameExplorerService iterates over species items, not lists
