### ISSUE TITLE
Deleting a taxon from list deleted all contents from fq column (Editing an fq has also resulted in deleted fq column content too)

### ISSUE THREAD

**Issue by turley85** [AtlasOfLivingAustralia/specieslist-webapp#311]
I was reviewing this list (https://lists.ala.org.au/speciesListItem/list/dr27347) to amend the -taxon query. I found a taxon that was erroneously including in the list. As such, I clicked the delete button for that taxon. 

Upon the list reloading, all contents from the fq column had been deleted.

**Comment by kylie-m** [comment]
In replicating this issue, I've had slightly different results, on _production_. In this case, the entire fq column has been removed, no longer visible

Steps to generate the issue:
1. go to https://lists.ala.org.au/speciesListItem/list/dr27336
2. I started with 4 taxa on the list. The top one had  `cl927:*` for fq field
3. Added `placeholder` string text to another taxa on the list. save, refreshed page
4. Removed cl927 from fq of first taxa. save, refreshed page
5. check page, fq column missing

**Comment by kylie-m** [comment]
Also tried to replicate the issue on https://lists.ala.org.au/speciesListItem/list/dr27372, this list seemed to be error free, as i began with content in all 3 fq fields. I have deleted fq content for one taxa, refreshed, repeated, and the fq content for one taxa remains

**Comment by kylie-m** [comment]
screenshot

![Screenshot 2024-07-23 at 2 57 24 pm](https://github.com/user-attachments/assets/e04cda72-c869-48ba-bd59-30baa4e7acf8)

**Comment by kylie-m** [comment]
The workaround of reloading a list has been discussed - in the meantime, @turley85 is reloading lists, to be able to proceed with testing.

**Comment by adam-collins** [comment]
Item to test, confirm that the now undeleted item does not appear in the list export e.g. https://lists-test.ala.org.au/ws/speciesListItems/dr22791?includeKVP=true

**Comment by kylie-m** [comment]
I gave this a spin on _test_ and it is working ok for me. @turley85 could you test it too and see how it goes using a list on _test_ ? My steps are below for reference:

1. edit fq column on a list, save, reload
2. check the fq column remains visible, contents update correctly for the taxa you edited, and contents of fq column for other taxa remain unchanged 
3. repeat 1-2 times
4. download the species list csv and check -  fq column should be there, and contents should be correct for each row

**Comment by kylie-m** [comment]
Also confirming that editing the fq column updates the list export - e.g URL: https://lists-test.ala.org.au/ws/speciesListItems/dr22791?includeKVP=true

**Comment by turley85** [comment]
I just had a look at lists in test and it appears to be working as intended there.
