### ISSUE TITLE
webservices to support facetting

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/specieslist-webapp#37]
E.g. http://lists.ala.org.au/ws/speciesListItems/dr781

should also return data for facets seen on web page: 

http://lists.ala.org.au/speciesListItem/list/dr781

and support pagination and filtering, e.g. 

http://lists.ala.org.au/speciesListItem/list/dr781

**Comment by nickdos** [comment]
Fixed in commit ded73af

**Comment by temi** [comment]
nick says, previously intended for MDBA but got around it. It is not needed anymore.
