### ISSUE TITLE
Pagination/sorting issues in list

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/specieslist-webapp#40]
Bug reported by user:

> On 27 Aug 2015, at 2:14 pm, Ingrid Bonrud Jakobsen <ingridbjakobsen@gmail.com> wrote:
Dear support team,
I tried to use your database today and ran into a few issues. This is for the Census of Queensland Flora 2013, Vascular plants.
Firstly, when I selected ferns, I got an error page. (At bottom of email)
http://lists.ala.org.au/speciesListItem/list/dr891?fq=kvp%20Phylum:Ferns%20&%20Allies
It looks like an SQL formatting issue and consequent dump to me, and I have worked with SQL in my time, but I assumed this website was for general public use.
Secondly as a much lesser (but annoying) issue, if I select another group, 
http://lists.ala.org.au/speciesListItem/list/dr891?fq=family:Proteaceae
and then change the number of items to show per page, the display returns to the top level. 
http://lists.ala.org.au/speciesListItem/list/dr891?max=50&sort=itemOrder&order=&offset=0
It does not seem to be possible to show more than 10 results per page for any selection, which makes that a very misleading little button.
I'm afraid I'm going to look for some other websites to help me with the actual plant thing I wanted to look up today, sorry.
I did work on a project once where we got as far as arguing whether we were going to use Rails or Django before money ran out, so I appreciate the issues you are facing :-).
Cheers, Ingrid

When closing issue, please send email to the user and let them know that fix has been deployed.

**Comment by Tasilee** [comment]
The inability to sort on at least a few key columns in large lists is a problem. The ordering of species in the list is effectively random (as far as the user is concerned). Using Genus in Refine doesn't help as that list isn't sorted alpha. Suggest the ability to be able to sort on at least Scientific name and Author.

**Comment by sat01a** [comment]
@temi Can you pls add upsource url?

**Comment by temi** [comment]
https://upsource.ala.org.au/specieslist-webapp/review/SW-CR-4
