### ISSUE TITLE
recognise hyperlinks in content

### ISSUE THREAD

**Issue by M-Nicholls** [AtlasOfLivingAustralia/specieslist-webapp#42]
Hyperlinks just show up as text.  e.g. http://www.biodiversitylibrary.org/item/8368#page/41  should be an active hyperlink.  current workaround is to format content into HTML but that's not a good solution and requires additional knowledge to do.

**Comment by ben3000** [comment]
Should I wrap the URL in a phishing checker link, just in case we get dodgy links?
