### ISSUE TITLE
lists upload to parse camel case headers

### ISSUE THREAD

**Issue by M-Nicholls** [AtlasOfLivingAustralia/specieslist-webapp#50]
currently lists tool shows headers exactly as loaded: 

e.g. BreedingHabitatTemperateWetSclerophyllForestAndWoodland
should parse as 
Breeding Habitat Temperate Wet Sclerophyll Forest And Woodland

**Comment by ben3000** [comment]
What should happen if the header column name is e.g. occurrenceStatus? Would you prefer that these were left as-is?

**Comment by ben3000** [comment]
See https://github.com/AtlasOfLivingAustralia/specieslist-webapp/commit/4f61e4ad879cb2b0b3429ba10e2180c73d97b386.
