### ISSUE TITLE
Allow linking to a species "view" on a list page

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/specieslist-webapp#52]
E.g. http://lists.ala.org.au/speciesListItem/list/dr490#Borya+mirabilis

should open the species list page and display the modal popup, as if the user had clicked the "info" icon next to `Borya mirabilis`.

![image](https://cloud.githubusercontent.com/assets/532845/17801485/caacd78a-662d-11e6-95bd-d181206894be.png)

**Comment by ben3000** [comment]
Is it necessary that this is done as a pop-up modal?

**Comment by nickdos** [comment]
The functionality is already there, implemented as a popup... this issue is to trigger it via URL hash detection.

**Comment by nickdos** [comment]
I'd rather not re-implement existing functionality if at all possible... if there is a compelling reason to do it some other way, then I'm open to it.

**Comment by ben3000** [comment]
OK
