### ISSUE TITLE
Clicking the Download button for a species list a second time causes the popup window to display the wrong content

### ISSUE THREAD

**Issue by ben3000** [AtlasOfLivingAustralia/specieslist-webapp#54]
Click on a species list, click the download button, close the popup window that appears, click the download button again. The resulting popup window contains a partial load of the species list itself, plus the console lists a number of errors indicating that the page was only partially loaded.

![screenshot from 2016-09-02 16 41 46](https://cloud.githubusercontent.com/assets/1963681/18197907/5efee96a-712c-11e6-9829-aa762d801fe9.png)

**Comment by djtfmartin** [comment]
This is fixed on master with this commit

https://github.com/AtlasOfLivingAustralia/specieslist-webapp/commit/163c9648b9c946f5f788be7bc85a49b85b953b98

The problem was with a bug with a more recent version of jquery when used with fancybox 1.3.4
