### ISSUE TITLE
Logger URL is hardcoded

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/specieslist-webapp#87]
The logger URL is currently hardcoded:

https://github.com/AtlasOfLivingAustralia/specieslist-webapp/blob/master/grails-app/services/au/org/ala/specieslist/LoggerService.groovy#L10

**Comment by djtfmartin** [comment]
Fixed in this commit i think

https://github.com/AtlasOfLivingAustralia/specieslist-webapp/commit/98f0aa971bd1caf391c1d10fea74098216e89441#diff-e847b9b5307f00d7ee248fb11b8c32cb

**Comment by ansell** [comment]
Tested the fix for this as part of https://github.com/AtlasOfLivingAustralia/spatial-hub/issues/265
